files:

  dirty_data_file: /home/daniel/Data/firstdraftgis_export.tsv
  dirty_training_file: /home/daniel/Data/training_dirty.tsv
  dirty_testing_file: /home/daniel/Data/testing_dirty.tsv
  processed_training_file: /home/daniel/Data/marge_processed_training_data.tsv
  processed_testing_file: /home/daniel/Data/marge_processed_testing_data.tsv
  testing_path: /home/daniel/Data/marge_testing_data.tsv

training:
  rowcount: 100000

testing:
  nrows: 100000

models:

  first_pass:
    path: /home/daniel/Data/first_pass.pickle
    columns:
      - has_enwiki_title
      - importance
      - pop_is_zero
      - has_population_over_1_million

  second_pass:
    path: /home/daniel/Data/second_pass.pickle
    columns:
      - country_code_frequency
      - probability
      #- has_enwiki_title
      #- importance
      #- is_admin
      #- has_population_over_1_million
      #- has_population_over_1_thousand
      #- has_population_over_1_hundred
      #- percent_fields_complete
