files:

  dirty_data_file: /tmp/firstdraftgis_export.tsv
  dirty_training_file: ~/Data/training_dirty.tsv
  dirty_testing_file: ~/Data/testing_dirty.tsv
  processed_training_file: ~/Data/marge_processed_training_data.tsv
  processed_testing_file: ~/Data/marge_processed_testing_data.tsv
  testing_path: ~/Data/marge_testing_data.tsv
  cooccurrences_path: ~/Data/cooccurrences.pickle
  is_a_place_frequency_counter: ~/Data/is_a_place_frequency.pickle

training:
  rowcount: 100000

testing:
  nrows: 100000

models:

  first_pass:
    path: ~/Data/first_pass.pickle
    columns:
      - has_enwiki_title
      - importance
      - population_is_zero
      - has_population_between_1_and_1_thousand
      - has_population_between_1_thousand_and_1_million
      - has_population_between_one_milion_and_ten_million
      - has_population_over_ten_million

  second_pass:
    path: ~/Data/second_pass.pickle
    columns:
      #- pairing score
      #- get median percentage of usage with each other place versus alternatives
      # so basically how likely is it that this place is used based on context of other places
      # versus another
      - median_cooccurrence
      - score_1
  
  third_pass:
    path: ~/Data/third_pass.pickle
    columns:
      - score_2
      - is_a_place_frequency
      #- length_of_normalized_name
