files:

  dirty_data_file: /tmp/firstdraftgis_export.tsv
  dirty_training_file: /tmp/training_dirty.tsv
  dirty_testing_file: /tmp/testing_dirty.tsv
  processed_training_file: /tmp/marge_processed_training_data.tsv
  processed_testing_file: /tmp/marge_processed_testing_data.tsv
  testing_path: /tmp/marge_testing_data.tsv

models:

  first_pass:
    path: /tmp/first_pass.pickle
    columns:
      - has_enwiki_title
      - importance
      - has_population_over_1_million
      - has_population_over_1_thousand
      - has_population_over_1_hundred

  second_pass:
    path: /tmp/second_pass.pickle
    columns:
      - country_code_rank
      - has_enwiki_title
      - importance
      - has_population_over_1_million
      - has_population_over_1_thousand
      - has_population_over_1_hundred
